services:
  - type: web
    name: mental-health-analysis
    env: python
    region: oregon  # or singapore, frankfurt, ohio
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: mental_health_db
          property: connectionString
    healthCheckPath: /
    autoDeploy: true

databases:
  - name: mental_health_db
    plan: free
    region: oregon